sudo: required
language: node_js
node_js:
  - "10"
cache:
  - yarn
  - npm

stages:
  - test
  - build

branches:
  only:
  - master

jobs:
  include:
    - stage: test
      script: yarn test:ci
      after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: build
      script: yarn build:ngx-breadcrumbs
    - stage: build
      script: yarn build:ngx-test-utils
    - stage: build
      script: yarn build:ngx-file-upload
    - stage: build
      script: yarn build:ngx-k-code
    - stage: build
      script: yarn build:demo
