sudo: required
language: node_js
node_js:
  - "10"
cache: yarn

stages:
  - test
  - build

branches:
  only:
  - master

jobs:
  include:
    - stage: test
      script: npm run test:ci
    - stage: build
      script: npm run build:ngx-breadcrumbs
    - stage: build
      script: npm run build:ngx-test-utils
    - stage: build
      script: npm run build:ngx-file-upload
    - stage: build
      script: npm run build:demo
