sudo: required
language: node_js
node_js:
  - "16"
cache:
  npm: false
  directories:
    - ./.yarn/cache

env:
  - CI=true YARN_ENABLE_IMMUTABLE_INSTALLS=false

stages:
  - build

branches:
  only:
  - master

before_install:
  - corepack enable
  - yarn set version 3.2.0
  - yarn --version

install: yarn

jobs:
  include:
    - stage: build
      script: yarn build:ngx-breadcrumbs
    - stage: build
      script: yarn build:ngx-skeleton-loader
    - stage: build
      script: yarn build:ngx-file-upload
    - stage: build
      script: yarn build:ngx-k-code
    - stage: build
      script: yarn build:ngx-mat-popover
    - stage: build
      script: yarn build:ngx-signature-pad
