sudo: required
language: node_js
node_js:
  - "12"
cache:
  - yarn
  - npm

stages:
  - test
  - build

branches:
  only:
  - master

jobs:
  include:
    - stage: test
      script: npm run test:ci
    - stage: build
      script: npm run build:ngx-breadcrumbs
    - stage: build
      script: npm run build:ngx-test-utils
    - stage: build
      script: npm run build:ngx-file-upload
    - stage: build
      script: npm run build:ngx-k-code
    - stage: build
      script: npm run build:demo
